name: ci
on:
  # Build on demand:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Docker image tag'     
        required: true  
  # Build on push:
  push:
    branches:
      - master
      - test
  # Publish `vx.y.z` tags as releases:
  release:
    types: [published]

jobs:
  build_and_push:
    name: Build and push docker image to Docker Hub
    runs-on: ubuntu-latest
    #if: github.event_name == 'push'
    steps:

#     -
#        name: Check out the repo
#        uses: actions/checkout@v2
#      -
#        name: Build and push
#        id: docker_build
#        uses: docker/build-push-action@v2
#        with:
#          #username: ${{ secrets.DOCKERHUB_USERNAME }}
#          #password: ${{ secrets.DOCKERHUB_TOKEN }}
#          repository: testillano/nghttp2
#          tag_with_ref: true

          #push: true
          #tags: testillano/nghttp2:latest
      -
        name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          #logout: true
#      -
#        name: Build
#        id: docker_build
#        uses: docker/build-push-action@v2
#        with:
#          repository: testillano/nghttp2
#          tag_with_ref: true
#          #push: true
#          #tags: testillano/nghttp2:latest
#      -
#        name: Push image
#        run: |
#          IMAGE_ID=docker.io/testillano/nghttp2
#
#          # Strip git ref prefix from version
#          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
#
#          # Strip "v" prefix from tag name
#          [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')
#
#          # Use Docker `latest` tag convention
#          [ "$VERSION" == "master" ] && VERSION=latest
#
#          echo IMAGE_ID=$IMAGE_ID
#          echo VERSION=$VERSION
#
#          docker tag nghttp2 $IMAGE_ID:$VERSION
#          docker push $IMAGE_ID:$VERSION






