name: ci

on:
  push:
    branches: test

env:
  IMAGE_NAME: nghttp2

jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      -
        name: Test variables
        run: |
          echo USERNAME is ${{ secrets.DOCKERHUB_USERNAME }} AND TOKEN IS ${{ secrets.DOCKERHUB_TOKEN }}
          
      -
        name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          logout: true
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: testillano/$IMAGE_NAME:latest
